"""add medical alerts

Revision ID: 253eeca41994
Revises: d5e1faf7cca4
Create Date: 2026-04-27 11:24:41.241615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '253eeca41994'
down_revision = 'd5e1faf7cca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_alerts_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_alerts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_alerts_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_alerts_user_id'))
        batch_op.drop_index(batch_op.f('ix_medical_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_medical_alerts_source'))
        batch_op.drop_index(batch_op.f('ix_medical_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_medical_alerts_created_at'))
        batch_op.drop_index(batch_op.f('ix_medical_alerts_alert_type'))

    op.drop_table('medical_alerts')
    # ### end Alembic commands ###
