"""add medications and dose logs

Revision ID: 7ec7b4e60db7
Revises: b62751217fda
Create Date: 2026-04-27 10:37:21.541473

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ec7b4e60db7'
down_revision = 'b62751217fda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medication_dose_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medication_dose_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medication_dose_logs_medication_id'), ['medication_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_dose_logs_scheduled_time'), ['scheduled_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_dose_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dose_mg', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('frequency_hours', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('first_dose_time', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('with_food', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_medications_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('medications_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('time')
        batch_op.drop_column('frequency')
        batch_op.drop_column('dose')
        batch_op.drop_column('notes')
        batch_op.drop_column('last_taken_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_taken_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dose', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('frequency', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('time', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('medications_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_medications_user_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('with_food')
        batch_op.drop_column('first_dose_time')
        batch_op.drop_column('frequency_hours')
        batch_op.drop_column('dose_mg')

    with op.batch_alter_table('medication_dose_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medication_dose_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_medication_dose_logs_scheduled_time'))
        batch_op.drop_index(batch_op.f('ix_medication_dose_logs_medication_id'))

    op.drop_table('medication_dose_logs')
    # ### end Alembic commands ###
