"""add users and cardiovascular risk tables

Revision ID: b62751217fda
Revises: 
Create Date: 2026-04-27 06:01:22.426807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b62751217fda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diseases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('cardiovascular_risk_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=20), nullable=False),
    sa.Column('has_diabetes', sa.Boolean(), nullable=False),
    sa.Column('is_smoker', sa.Boolean(), nullable=False),
    sa.Column('systolic_bp', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('total_cholesterol', sa.Integer(), nullable=False),
    sa.Column('age_bucket', sa.Integer(), nullable=True),
    sa.Column('systolic_bucket', sa.Integer(), nullable=True),
    sa.Column('cholesterol_bucket', sa.Integer(), nullable=True),
    sa.Column('risk_percent', sa.Float(), nullable=True),
    sa.Column('risk_display', sa.String(length=20), nullable=True),
    sa.Column('risk_category', sa.String(length=50), nullable=True),
    sa.Column('risk_category_label', sa.String(length=100), nullable=True),
    sa.Column('is_applicable', sa.Boolean(), nullable=False),
    sa.Column('calculation_message', sa.String(length=255), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cardiovascular_risk_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cardiovascular_risk_history_calculated_at'), ['calculated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cardiovascular_risk_history_user_id'), ['user_id'], unique=False)

    op.create_table('cardiovascular_risk_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=20), nullable=False),
    sa.Column('has_diabetes', sa.Boolean(), nullable=False),
    sa.Column('is_smoker', sa.Boolean(), nullable=False),
    sa.Column('systolic_bp', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('total_cholesterol', sa.Integer(), nullable=False),
    sa.Column('age_bucket', sa.Integer(), nullable=True),
    sa.Column('systolic_bucket', sa.Integer(), nullable=True),
    sa.Column('cholesterol_bucket', sa.Integer(), nullable=True),
    sa.Column('risk_percent', sa.Float(), nullable=True),
    sa.Column('risk_display', sa.String(length=20), nullable=True),
    sa.Column('risk_category', sa.String(length=50), nullable=True),
    sa.Column('risk_category_label', sa.String(length=100), nullable=True),
    sa.Column('is_applicable', sa.Boolean(), nullable=False),
    sa.Column('calculation_message', sa.String(length=255), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cardiovascular_risk_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cardiovascular_risk_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('emergency_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('relationship', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('systolic', sa.Integer(), nullable=False),
    sa.Column('diastolic', sa.Integer(), nullable=False),
    sa.Column('symptoms_json', sa.JSON(), nullable=False),
    sa.Column('risk_factors_json', sa.JSON(), nullable=False),
    sa.Column('pressure_category', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('prediagnosis', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('matched_rules', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('dose', sa.String(length=50), nullable=False),
    sa.Column('time', sa.String(length=10), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_taken_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('critical_alerts', sa.Boolean(), nullable=False),
    sa.Column('ai_trends', sa.Boolean(), nullable=False),
    sa.Column('medication_reminders', sa.Boolean(), nullable=False),
    sa.Column('missed_doses', sa.Boolean(), nullable=False),
    sa.Column('daily_measurement', sa.Boolean(), nullable=False),
    sa.Column('health_tips', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('risk_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('symptoms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('symptom_type', sa.String(length=50), nullable=False),
    sa.Column('is_alarm', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('birth_date', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=30), nullable=True),
    sa.Column('weight_kg', sa.String(length=20), nullable=True),
    sa.Column('height_m', sa.String(length=20), nullable=True),
    sa.Column('blood_type', sa.String(length=20), nullable=True),
    sa.Column('diagnosis', sa.String(length=150), nullable=True),
    sa.Column('diagnosis_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    op.drop_table('symptoms')
    op.drop_table('risk_factors')
    op.drop_table('notification_preferences')
    op.drop_table('medications')
    op.drop_table('evaluations')
    op.drop_table('emergency_contacts')
    with op.batch_alter_table('cardiovascular_risk_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cardiovascular_risk_profiles_user_id'))

    op.drop_table('cardiovascular_risk_profiles')
    with op.batch_alter_table('cardiovascular_risk_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cardiovascular_risk_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_cardiovascular_risk_history_calculated_at'))

    op.drop_table('cardiovascular_risk_history')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('diseases')
    # ### end Alembic commands ###
