"""add vital records

Revision ID: d5e1faf7cca4
Revises: 7ec7b4e60db7
Create Date: 2026-04-27 10:48:17.729995

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd5e1faf7cca4'
down_revision = '7ec7b4e60db7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vital_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('systolic_bp', sa.Integer(), nullable=False),
    sa.Column('diastolic_bp', sa.Integer(), nullable=False),
    sa.Column('heart_rate_bpm', sa.Integer(), nullable=False),
    sa.Column('symptoms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('symptom_labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bp_category', sa.String(length=60), nullable=False),
    sa.Column('bp_category_label', sa.String(length=100), nullable=False),
    sa.Column('systolic_category', sa.String(length=60), nullable=False),
    sa.Column('diastolic_category', sa.String(length=60), nullable=False),
    sa.Column('is_isolated_systolic', sa.Boolean(), nullable=False),
    sa.Column('has_alarm_symptoms', sa.Boolean(), nullable=False),
    sa.Column('urgency_level', sa.String(length=20), nullable=False),
    sa.Column('initial_assessment', sa.Text(), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vital_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vital_records_bp_category'), ['bp_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_vital_records_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vital_records_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vital_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vital_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_vital_records_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_vital_records_bp_category'))

    op.drop_table('vital_records')
    # ### end Alembic commands ###
